repos:
-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: 'v0.32.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: yapf

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.3.0'
    hooks:
    -   id: mypy
        name: mypy py3.9
        args: ['--python-version=3.9']
    -   id: mypy
        name: mypy py3.10
        args: ['--python-version=3.10']
    -   id: mypy
        name: mypy py3.11
        args: ['--python-version=3.11']
    -   id: mypy
        name: mypy py3.12
        args: ['--python-version=3.12']


-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
