name: Test whl install
on:
  # workflow_dispatch: # Allow manual triggers
  #   inputs:
  #     python_version:
  #       description: 'Python version'
  #       required: false
  #       default: '3.10'
  #     version:
  #       type: string
  #       required: true
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: update version
        shell: bash
        run: |
          echo "__version__ = '1.1.0'" >  edgemdt_cl/version.py
          echo "print edgemdt_cl/version.py"
          cat edgemdt_cl/version.py
      - name: Build wheel
        shell: bash
        run: |
          pip install build
          python -m build --wheel
      - name: Find WHL file
        run: |
          echo "whl_file=$(find . -iname '*.whl')" >> $GITHUB_ENV
          echo $whl_file
      - name: Install WHL file
        run: |
          pip install "$whl_file"
          pip list
      - name: Uninstall WHL file
        run: |
          pip uninstall -y "$whl_file"
          pip list
      - name: Install WHL[tf] file
        run: |
          pip install "$whl_file[tf]"
          pip list